### ISSUE TITLE
visreg ignores strip.names if gg=TRUE in an overlay=TRUE  plot

### ISSUE THREAD

**Issue by tbates** [pbreheny/visreg#104]
`visreg()` should use `strip.names` to label levels in the legend of an  `overlay=TRUE`  plot
This works in lattice output, but `strip.names` is ignored  when `gg=TRUE`

Getting the legend re-labelled is complex post-hoc for the user...

```R
m1 = lm(Ozone ~ Solar.R + Wind * Temp, data=airquality)
visreg(m1, "Temp", by="Wind", overlay=TRUE, strip.names=c("Low C", "Mid C", "High C"))

```

gg=TRUE version ignores `strip.names`
<img width="735" alt="image" src="https://user-images.githubusercontent.com/736156/201119760-bdf7e04a-540e-48c4-b178-5d38ffa08c13.png">

lattice version uses the `strip.names`:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/736156/201120081-589c7044-ab47-47ee-9de3-95a496d6bbf7.png">

**Comment by pbreheny** [comment]
Thanks for pointing this out and providing a reproducible example! This is fixed now in version 2.7.0.4.

**Comment by tbates** [comment]
Many thanks @pbreheny: Any chance this version or higher could be pushed to CRAN? (so code works for non-github users?)

**Comment by pbreheny** [comment]
@tbates: Yes, I absolutely need to do that! This time of year (end of academic semester) is very hectic, but I plan to put the next version of visreg on CRAN by the end of the month.
