### ISSUE TITLE
shape-coded dots 

### ISSUE THREAD

**Issue by felixpleiva** [pbreheny/visreg#105]
Hi all,

Thank you very much for this fantastic package. 

I have this model and I want to shape code by stock

fit1<-lmer(fresh_mass_delta ~ temperature * cell_area_delta + oxygen * cell_area_delta + sex + (1|stock),REML = FALSE, data=dat)

visreg(fit1,"cell_area_delta",by="temperature",cond=list(oxygen=10),overlay=TRUE,
   print.cond=TRUE,legend = FALSE,
       points=list(col=c("#2c7fb870", "#de2d2670"),pch=16,cex=1.4),
       line=list(col=c("#2c7fb8", "#de2d26"), lwd=4),
       xlab="Standardised cell area (%)", ylab="Standardised fresh mass (%)",
       ylim=c(-50,50),xlim=c(-50,50),
       xaxs = "i",yaxs = "i",#force origin of our x- and y-axes
       cex.axis=1.5,cex.lab=1.5)
abline(h=0,lty=2,lwd=2)
abline(v=0,lty=2,lwd=2)

#Draw a polygon defining an area on the graph
xx = c(-49.8,-49.8,49.8,49.8)
yy = c(35,49.8,49.8,35)
polygon(xx,yy, col = 'grey90', border = NA)
legend("bottomright", legend=c("17°C", "25°C"),
       lty = 1,lwd=4, bty="n",
       col=c("#2c7fb8", "#de2d26"),cex=1.4)
text(0,42.5,"Hypoxia (10 kPa)",font=2,cex=1.5)

![imagen](https://user-images.githubusercontent.com/57069034/212916663-db8d5f3e-09ea-4206-93c4-a1975ba3909b.png)

**Comment by pbreheny** [comment]
Closing this issue since I never heard back from you.
