### ISSUE TITLE
Changing color of the bands in visreg

### ISSUE THREAD

**Issue by rahapazoki** [pbreheny/visreg#12]
How can I change the color of the bands and remove the ticks in visreg (figure 7 of the visreg manual?)

**Comment by pbreheny** [comment]
Partial residuals and rugs are controlled through the `partial` and `rug` options; plotting options are controlled by `fill.par`, `line.par`, and `points.par`.  For example,

```
airquality$Heat <- cut(airquality$Temp,3,labels=c("Cool","Mild","Hot"))
fit <- lm(Ozone ~ Solar.R + Wind*Heat, data=airquality)
visreg(fit, "Wind", by="Heat", overlay=TRUE, partial=FALSE, rug=FALSE,
       fill.par=list(col=c('purple', 'green', 'black')))
```

See the help files for more details.
