### ISSUE TITLE
visreg breaking code when passing gam models from gamm4 

### ISSUE THREAD

**Issue by pmotta** [pbreheny/visreg#19]
I'm using visreg 2.2-2 over a gam model from gamm4 package and when I try to obtain a dataset from my gam model object, I get this error:

 my code is  (although it isn't reproducible):

model <- gamm4(data=data_val, formula=log10(price)~age_cat+sex+deg_all+pop.den+bov.den+urban+orig_div+s(week,k=26),random=~(1|Market))

plot <- visreg(model$gam, type = "contrast", data=data_val)
Error in eval(expr, envir, enclos) : object 'age_cat' not found

I've read this post and followed the advice but could not get the desired output yet
https://github.com/pbreheny/visreg/issues/13

**Comment by pbreheny** [comment]
I can confirm that this is a bug.  Here is a reproducible example; the following works:

```
x <- runif(100)
fac <- factor(sample(1:20,100,replace=TRUE))
eta <- x^2*3 + as.numeric(fac)/20
y <- rpois(100,exp(eta))
fit <- gamm4(y~s(x),family=poisson,random=~(1|fac))
visreg(fit$gam, "x")
```

But if you try a contrast plot, we get an error message

```
> visreg(fit$gam, "x", type="contrast")
Error in x$X %*% b[is.finite(b)] + rr : non-conformable arrays
```

I'll post again when this is fixed.

**Comment by pmotta** [comment]
Thank you very much keeping posted
