### ISSUE TITLE
Custom axes in visreg

### ISSUE THREAD

**Issue by danawanzer** [pbreheny/visreg#23]
I was wondering if it is possible to do custom x- and y-axes in visreg. I saw code to do it in visreg2d but could not figure out how to do it in visreg. Essentially, the plots are currently extrapolating my y-axis beyond possible values (possible values range from 0 to 10 but it is plotting the y-axes from -5 to 15). If this is possible currently, I'd appreciate suggestions on how to code this. Thanks!

**Comment by pbreheny** [comment]
This works the same way in visreg as with any R plot:

```r
fit <- lm(Ozone ~ Solar.R + Wind + Temp,data=airquality)
visreg(fit, "Wind", ylim=c(30, 80))
```

Maybe I'm not understanding you?

**Comment by danawanzer** [comment]
Thank you! I am still fairly new to R and haven't learned much in the way
of plotting via R. I appreciate your help!

Best,
Dana Linnell Wanzer, M.A.
Evaluation, Research, and Statistics Consultant
Evaluation Doctoral Student at Claremont Graduate University
danawanzer.com | linkedin.com/in/danawanzer
<https://www.linkedin.com/in/danawanzer> | (760) 835-3604
