### ISSUE TITLE
Overlay plot on other visreg

### ISSUE THREAD

**Issue by sluijs** [pbreheny/visreg#26]
It would be nice if you could overlay one `visreg` plot with another. For example if I fit two models:
`y ~ fp(x1) + fp(x2) + factor(x3)` and `y ~ bs(x1, df = 3) + bs(x2) + factor(x3)`, then it would be nice to overlay the functional form of fp(x1) and bs(x1) or with the normal linear variant. Thanks for the nice package!

**Comment by pbreheny** [comment]
Do you mean something like this?

```r
n <- 100
x <- runif(n, 0, 3)
y <- rnorm(n, 3*cos(x^2))
plot(x,y)

require(splines)
fit1 <- lm(y ~ bs(x, df=5))
fit2 <- lm(y ~ ns(x, df=3))

require(visreg)
v1 <- visreg(fit1)
v2 <- visreg(fit2)

matplot(v1$fit$x, cbind(v1$fit$visregFit, v2$fit$visregFit),
        lty=1, col=c("#FF4E37FF", "#008DFFFF"), type='l', lwd=3,
        xlab="x", ylab="y")
with(v1$res, points(x, visregRes, col='gray', cex=0.7, pch=19))
```
![v2](https://cloud.githubusercontent.com/assets/1858089/23871791/db0eda2e-07f9-11e7-8b68-c51fd38249d3.png)

I can see what you mean, that such a plot could be useful, but in general, there would be no guarantee that overlaying two models would make any sense as something to look at.  I guess I can keep thinking about it, but I guess at the moment I'm a bit unsure how useful a feature this would be.
