### ISSUE TITLE
working paper: "effects" package and partial residuals

### ISSUE THREAD

**Issue by rdiaz02** [pbreheny/visreg#28]
The working paper for visreg, [Visualization of Regression Models Using visreg](http://myweb.uiowa.edu/pbreheny/publications/visreg.pdf) says on p.2 "However, it is worth pointing out while `effects` can produce plots similar to `visreg`, it does not offer the ability to plot partial residuals." I do not think that is correct nowadays, though: `effects` can plot partial residuals. For instance, `?effects-package` shows "For linear and generalized linear models it is also possible to plot partial residuals". And there is argument `partial.residuals` to function `effect` and `plot.eff` (or `summary.eff`). (The definition of partial residuals, however, is different, as `effects` uses working residuals --- see also https://github.com/pbreheny/visreg/issues/27).

**Comment by pbreheny** [comment]
Thank you very much for pointing this out -- I'm not sure if this is a new feature in `effects` or if I somehow missed it, but that line in the paper is certainly no longer correct.  I am currently working on a new draft, and have corrected this error.  Thanks again for bringing this to my attention.
