### ISSUE TITLE
knitr + RGL: Issues with visreg's visreg2d function

### ISSUE THREAD

**Issue by fgnu** [pbreheny/visreg#3]
I am trying to create an RGL plot using the `visreg2d` function of the `visreg` package in R, to include into an HTML document created by running `knitr` on an RMarkdown file. 

I am able to get RGL plots from `rgl` package functions `plot3d` and `spheres3d` but not from a call to `visreg2d(..., plot.type = "rgl")` in my HTML document.

Here is a sample RMarkdown file, built up from the example [here][1]:

    ---
    output:
      html_document:
        self_contained: no
    ---
    ```{r setup, results='asis'}
    library(knitr)
    library(rsm)
    library(visreg)
    
    knit_hooks$set(webgl = hook_webgl)
    cat('<script type="text/javascript">', readLines(system.file('WebGL', 'CanvasMatrix.js', package = 'rgl')), '</script>', sep = '\n')
    ```
    
    This works fine.
    
    ```{r testgl, webgl=TRUE}
    x <- sort(rnorm(1000))
    y <- rnorm(1000)
    z <- rnorm(1000) + atan2(x,y)
    plot3d(x, y, z, col=rainbow(1000))
    ```
    
    This one also works.
    
    ```{r testgl2, webgl=TRUE}
    open3d()
    spheres3d(x, y, z, col=rainbow(1000))
    ```
    
    ```{r, webGL = TRUE}
    library(rsm)
    swiss2.lm <- lm(Fertility ~ Agriculture*Education, data = swiss)
    open3d()
    visreg2d(swiss2.lm, "Education", "Agriculture", plot.type = "rgl")
    ```

The calls to `plot3d` and `spheres3d` work but not the one to `visreg2d`. That is, even though locally I can see the RGL plot, it does not get embedded in my HTML document. Any advice on how to get that working will be appreciated.

----

Note: Cross-posted [here](http://stackoverflow.com/questions/26690138/r-knitr-rgl-issues-with-visregs-visreg2d-function).

  [1]: http://stackoverflow.com/q/23021317/1414455

**Comment by pbreheny** [comment]
This is just a typo -- you've typed `webGL = TRUE` instead of `webgl=TRUE`.

However, I will add that when I tried this on my machine, I had to reduce the resolution of the visreg plot (otherwise I ran into "stack space overflow" errors) using the `nn` option to `visreg2d (e.g., `nn=39`).

**Comment by fgnu** [comment]
:facepalm: Ok, thanks.
