### ISSUE TITLE
custom font size

### ISSUE THREAD

**Issue by pertor** [pbreheny/visreg#34]
I'm using the visreg2d function, and plot.type="image". Is there an easy way to change the font size of the color ramp (e.g. cex=1.5)?

**Comment by pbreheny** [comment]
`visreg` passes model information and plotting options on to `filled.contour`, which actually does the plotting.  So, looking at `?filled.contour`, it seems that the color ramp axis options are specified through the `key.axes` option.  Here's an example:

```r
fit <- lm(Ozone ~ Solar.R + Wind + Temp + I(Wind^2) + I(Temp^2) + I(Wind*Temp) +
            I(Wind*Temp^2) + I(Temp*Wind^2) + I(Temp^2*Wind^2), data=airquality)
visreg2d(fit, x="Wind", y="Temp", plot.type="image", key.axes=quote(axis(4, cex.axis=1.5)))
```

I believe this solves your question, so I'm closing the issue, but if that's not what you were trying to do, let me know and I can re-open it.
