### ISSUE TITLE
Add gg option to visreg2d?

### ISSUE THREAD

**Issue by grasshoppermouse** [pbreheny/visreg#37]
Any interest in adding a gg option to visreg2d with plot.type = "image"? Using geom_raster and geom_contour I was able to do this pretty easily with the object that visreg2d returns, but it would be nice to have this option built in.

My use case was that I wanted to overlay the actual data points on the contour plot:

![interaction](https://user-images.githubusercontent.com/7534138/31047076-d91545e8-a5b8-11e7-8742-1dc87c8aef89.png)

Thanks for the great package!

EDIT: Here is some code, if that helps:

```
fit <- lm(Ozone ~ Solar.R + Wind + Temp + I(Wind^2) + I(Temp^2) +
I(Wind*Temp)+I(Wind*Temp^2) + I(Temp*Wind^2) + I(Temp^2*Wind^2),
data=airquality)

v <- visreg2d(fit,x="Wind",y="Temp",plot.type="image")

df <- data.frame(x = v$x[row(vp$z)], y = v$y[col(vp$z)], z = c(v$z))
ggplot(df, aes(x, y)) + geom_raster(aes(fill=z)) + geom_contour(aes(z=z))
```

**Comment by pbreheny** [comment]
This is a fantastic suggestion, definitely on my to-do list.  Really sorry it took me so long to respond to this; was very busy with other things last semester.

**Comment by pbreheny** [comment]
With the latest commit, it is now possible to run

```
visreg2d(fit, "Wind", "Temp", plot.type="gg")
```

which produces

![vv-1](https://user-images.githubusercontent.com/1858089/36490007-ebf0a838-16ec-11e8-94cf-f3f9ae615a2a.png)

I didn't include contour lines by default, but they can be added afterwards if the user wants them via

```
visreg2d(fit, "Wind", "Temp", plot.type="gg") + geom_contour(aes(z=z), color="gray")
```

which produces

![vv-2](https://user-images.githubusercontent.com/1858089/36490208-63599a60-16ed-11e8-902f-bcd6070eb52b.png)

As you point out, one can also add points, etc., afterwards as well.

**Comment by grasshoppermouse** [comment]
Nice, thanks!
