### ISSUE TITLE
Managing visual appearance of strip in lattice plots

### ISSUE THREAD

**Issue by pbreheny** [pbreheny/visreg#4]
Jason Rohr (University of South Florida) writes: I can use the code

> `strip = strip.custom(bg = 0)`

to get the trellis strip to be white in the Lattice provided datasets (classic Fisher dataset), but this code doesn't seem to work for Visreg plots.

**Comment by pbreheny** [comment]
It's a bit thorny allowing users to access `strip.custom` directly, because `visreg` itself needs to set up the names in `strip.custom` appropriately.  So if you tried to pass your own `strip.custom` function, you'd override `visreg`'s use of that function, and the strips wouldn't be named correctly, unless you manually named them all (or I wrote some code to sort out the possible conflicts).  I'll keep thinking about whether there's a better way to handle this, but in general I think you're better off setting lattice's visual parameters outside of visreg (as opposed to trying to have visreg pass them to strip.custom and then pass that to xyplot):

> `fit <- lm(Ozone~ Solar.R + Wind*Temp, data=airquality)`
> `trellis.par.set(strip.background=list(col="white"))`
> `visreg(fit, "Wind", by="Temp")`

**Comment by jasonrohr** [comment]
Wonderful!  This works well.  Is this the same reason that the mfrow and layout functions don't work in visreg to produce multipaneled figures (i.e., because visreg itself is pulling together separate plots)?  Any work arounds within R (I can export and combine in ppt.)?

**Comment by pbreheny** [comment]
I'm not sure I understand what you mean here -- `visreg` works with `mfrow` and `layout`:

> `fit <- lm(Ozone ~ Solar.R + Wind + Temp,data=airquality)`
> `par(mfrow=c(1,3))`
> `visreg(fit, "Wind")`
> `visreg(fit, "Temp")`
> `visreg(fit, "Solar.R")`

> `layout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE))`
> `visreg(fit, "Wind")`
> `visreg(fit, "Temp")`
> `visreg(fit, "Solar.R")`

All of the above code works as expected for me.  If you're trying to combine a lattice plot with `mfrow`, however, that won't work.  The lattice package has its own mechanism for combining/arranging multiple trellis plots.  But visreg shouldn't interfere with that mechanism.

**Comment by pbreheny** [comment]
Actually, now that I check, visreg unfortunately *does* interfere with lattice's mechanism for arranging multiple plots, because it doesn't return the raw trellis object for you to work with.  This is now fixed on github, although it'll still be a few days to a week before the next release of visreg (2.1-1) is on CRAN.  But anyway, if you install the latest version, you should be able to run this:

> `fit <- lm(Ozone ~ Wind*Temp,data=airquality)`
> `v1 <- visreg(fit, "Wind", "Temp", plot=FALSE)`
> `v2 <- visreg(fit, "Temp", "Wind", plot=FALSE)`
> `trellis1 <- plot(v1, layout=c(3,1))`
> `trellis2 <- plot(v2, layout=c(3,1))`
> `plot(trellis1, split=c(1, 1, 1, 2), more=TRUE)`
> `plot(trellis2, split=c(1, 2, 1, 2))`

Is this what you were trying to accomplish?

**Comment by jasonrohr** [comment]
Yes, I was trying to have two multi-paneled interaction plots stacked using the mfrow or layout options.  I could get the mfrow function to work for single-paneled visreg objects but not for multipaneled trellis objects (i.e. interaction plots).  I am new to github and haven't accessed R packages through it yet.  I'll try to figure it out or wait until it is updated on CRAN.

**Comment by pbreheny** [comment]
Installing packages from github is pretty straightforward using the `devtools` package.  Just install the package and then

> `library(devtools)`
> `install_github("pbreheny/visreg")`

**Comment by jasonrohr** [comment]
I installed the updated package from github and the code worked.  Thanks a bunch!

**Comment by pbreheny** [comment]
OK, great -- glad to hear it.  I'm closing this issue and I'll open separate issues for the other things you brought up in your e-mail.
