### ISSUE TITLE
Option to plot on transformed scale

### ISSUE THREAD

**Issue by vspinu** [pbreheny/visreg#48]
If the model contains terms like `log(x)` or `scale(x)` would be nice to be able to plot on the transformed scale.

**Comment by vspinu** [comment]
This would parallel `transform.x` in `termplot`.

**Comment by pbreheny** [comment]
The argument to do this is called `xtrans`, as in the following:

```
fit <- lm(Ozone ~ log(Temp), data=airquality)
visreg(fit, xtrans=log)
```

**Comment by vspinu** [comment]
This is very different. It transforms all variables, but I want x axis on the tranformation scale which is already in the formula.

Something like:

```R
fit <- lm(resp ~ ns(x) + log(y) + scale(z))
visreg(fit, xtrans=TRUE)
```

Same result as `termplot(fit, transform.x=TRUE)`.

**Comment by pbreheny** [comment]
I guess I don't really see the point.  You can get those plots already:

```
visreg(fit, 'y', xtrans=log)
```

and so on.  Maybe you'd prefer a different syntax, but it doesn't seem to be the case where there's a plot you want to make and can't do so with `visreg`.

**Comment by vspinu** [comment]
> I guess I don't really see the point.

  1) I want to see all terms on the transformed scale at once. Looping through all the terms and calling visreg defeats the purpose of the handy visualization toolkit.
  2) Some terms are expansions, not transformations. Like ns, poly etc. For those extra computation and knowledge of the fitted object is needed. One cannot just `visreg(fit, "y", xtrans=ns)`. It doesn't make sense.

**Comment by pbreheny** [comment]
Well, I agree, `xtrans=ns` doesn't make any sense, so I don't understand what you want this option.  To me, the spline output for `termplot(fit, transform.x=TRUE)` borders on meaningless; I don't see how it is helpful in any way for understanding or troubleshooting the model.  Am I missing something?
