### ISSUE TITLE
No variation in partial residual plots

### ISSUE THREAD

**Issue by jasonrohr** [pbreheny/visreg#5]
Hi Patrick.  I am trying to understand why it is that when I run some mixed effects models and produce contrast plots, I get variation for some of my response variables in visreg plots but other response variables have all the data points falling directly on the regression line.  An example is provided below (script pasted, data pasted as an image, and visreg plots also pasted).  In the example below, I am attempting to conduct a random effects meta-analysis treating study as a random effect and weighting by the inverse of the variance estimate for the parameter of interest.  The response variables are parameters describing the shape of organismal performance curves and the predictors are acclimation temp., latitude, body size, habitat, and trophic position.  I suspect it has to do with the weights in the regression analysis that are somehow affecting the display of the partial residual plots.  I am just not sure if I should trust the plots that are being produced.  Thanks.

```
library(visreg)
library(nlme)

detach(mydatajl)
mydatajl<-read.delim("clipboard")
attach(mydatajl)

model1<-lme(joint_jl~AccTemp2*LogMass*absLatitude+Habitat+Trophic2,data=subset(mydatajl, Param=="E"), random = ~ 1 | DataSeriesID2, weights = varFixed(~ Var), na.action=na.omit,method="ML")
model2<-lme(joint_jl~AccTemp2*LogMass*absLatitude+Habitat+Trophic2,data=subset(mydatajl, Param=="tpk"), random = ~ 1 | DataSeriesID2, weights = varFixed(~ Var), na.action=na.omit, method="ML")
              
visreg(model1, "AccTemp2", "LogMass",  type = "contrast", points=list(col="black", cex=.75), line.par=list(lty=2, col="black", lwd=0.5), strip=FALSE, breaks=2,
       xlab="Acclimation temperature (degrees C)", cex.lab=1.25, cex.axis=1.25,
       ylab="Relative change in E parameter (degrees C)", cex.lab=1.25, cex.axis=1.25)

visreg(model2, "AccTemp2", "LogMass",  type = "contrast", points=list(col="black", cex=.75), line.par=list(lty=2, col="black", lwd=0.5), strip=FALSE, breaks=2,
       xlab="Acclimation temperature (degrees C)",
       ylab="Relative change in optimal temperature (degrees C)")
```

![image](https://cloud.githubusercontent.com/assets/11048715/6328851/870dcd72-bb39-11e4-96f5-76c3a0ff7f59.png)

![image](https://cloud.githubusercontent.com/assets/11048715/6328901/dce46a3a-bb39-11e4-9be0-8306f603f3a3.png)

![image](https://cloud.githubusercontent.com/assets/11048715/6328905/e485ce0a-bb39-11e4-8fea-aa00be7e9b67.png)

**Comment by pbreheny** [comment]
This isn't a problem with the display -- `visreg` is correctly displaying the model.  The problem is that the residuals *are* zero:

> `> range(residuals(model2))`
> `[1] -9.926502e-08  1.745643e-08`

You can trust the plot.  What you probably shouldn't trust is the model -- those residuals do not seem believable to me...nor do variances of 10^-30!

**Comment by jasonrohr** [comment]
Thanks.  Appreciate it.

On Wed, Feb 25, 2015 at 9:57 AM, Patrick Breheny <notifications@github.com>
wrote:

> This isn't a problem with the display -- visreg is correctly displaying
> the model. The problem is that the residuals *are* zero:
>
> > range(residuals(model2))
> [1] -9.926502e-08 1.745643e-08
>
> You can trust the plot. What you probably shouldn't trust is the model --
> those residuals do not seem believable to me...nor do variances of 10^-30!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbreheny/visreg/issues/5#issuecomment-75973902>.
>



-- 
Jason R. Rohr, Ph.D.
Associate Professor

Contact information:
University of South Florida
Department of Integrative Biology
SCA 110
4202 East Fowler Ave.
Tampa, FL 33620
Phone:  813-974-0156
Fax:  813-974-3263
Email: rohr@usf.edu
Webpage: http://biology.usf.edu/IB/faculty/index.aspx?name=jrohr
Website: http://shell.cas.usf.edu/rohrlab/index.html
Google Scholar site:
http://scholar.google.com/citations?user=yaRksUAAAAAJ&hl=en

“The most authentic thing about us is our capacity to create, to overcome,
to endure, to transform, to love and to be greater than our suffering.”
― Ben Okri
