### ISSUE TITLE
[conditional plots] Plot fitted line on top of residuals

### ISSUE THREAD

**Issue by vspinu** [pbreheny/visreg#50]
When thousands of residuals are plotted, they obscure the lines. Non-conditional plots do the right thing by plotting the fitted line on top of residuals, but conditional plots (`by="var"`) do it the other way around. 

Would be also nice to have transparency settings for residuals (particularly useful with `overlay=T`), as well as an option for subsampling in order to speed up big data plotting.

**Comment by webb-e** [comment]
I would like to second this suggestion.

**Comment by Patlane** [comment]
Hi!

I'm having the same issue. How to plot the lines over the residuals in the interaction plots? I'm using the gg=T option. If I use partials=FALSE, then the gg=T option does not have any effect any more and I get the lattice plot. I would prefer ggplot with the lines plotted over the residuals. Thank you very much!

**Comment by pbreheny** [comment]
Sorry this took so long, but it required a fair amount of internal restructuring of code.  This is now
* Handled consistently across all types of visreg plot
* By default, lines are always on top
* User has the option to reverse the default order if they wish by specifying `top="points"`
