### ISSUE TITLE
setting factor to centre on 0 for contrast plots

### ISSUE THREAD

**Issue by Maschette** [pbreheny/visreg#69]
Hi I tried to find it in other issues and the documentation, when x is a factor in contrast plots is there a way to set which x factor should be 0? as far as I can tell by default it selects the first one but I can't seem to find a way to change that. 

Cheers, 
Dale

**Comment by pbreheny** [comment]
You can use the `cond` argument for this.  For example,

```r
airquality$Heat <- cut(airquality$Temp, 3, labels=c("Cool","Mild","Hot"))
fit <- lm(Ozone ~ Heat, data=airquality)
visreg(fit, "Heat", type="contrast")                           # By default, uses first
visreg(fit, "Heat", type="contrast", cond=list(Heat="Mild"))   # Use a different category
```
