### ISSUE TITLE
Axis labels overlap axes in visreg2d persp plots

### ISSUE THREAD

**Issue by pbreheny** [pbreheny/visreg#7]
Jason Rohr (University of South Florida) writes: I really want to generate response surface plots (3d regression surface plots) with visreg, but I am having troubles with the visual appearance because the axis labels overlap with the number values on the axes and the number values often overlapped with the tickmarks.  To address this issue with standard 2d plots, you would use the mgp function, which is described nicely in the website [http://www.programmingr.com/content/controlling-margins-and-axes-oma-and-mgp/](http://www.programmingr.com/content/controlling-margins-and-axes-oma-and-mgp/).

**Comment by pbreheny** [comment]
`visreg` calls the `persp` function in the `graphics` package to produce this plot.  Unfortunately, the `persp` function does not allow as fine a level of control as you can get with 2D graphics; in particular, the `mgp` argument to `par()` does nothing.  This is nothing `visreg` is doing -- it's just a general limitation of the `persp()` function as currently implemented in `R`.  I'm not sure I know of anything to help you with the numbers overlapping the tick marks (other than laboriously entering all the tick marks manually using `text()` and `trans3d()`), but it's fairly easy to generate space between the labels and the numbers using newlines:

> `fit <- lm(Ozone~ Solar.R + Wind*Temp, data=airquality)`
> `visreg2d(fit, "Wind", "Temp", plot.type="persp")`
> `visreg2d(fit, "Wind", "Temp", plot.type="persp", xlab="\n\n\nWind", ylab="\n\n\nTemp", zlab="\n\n\nOzone")`

**Comment by jasonrohr** [comment]
Thanks Patrick.
