### ISSUE TITLE
support for rms objects

### ISSUE THREAD

**Issue by dylanbeaudette** [pbreheny/visreg#83]
The `rms` package has several fine methods for depiction of partial effects. The `visreg` package offers additional options and over-all, a simpler interface to the creation complex figures such as the outcome of a multi-nominal logistic regression.

![image](https://user-images.githubusercontent.com/624277/76453646-735aea80-6390-11ea-9c43-3257eca88148.png)

Thanks!

Here is a tiny example.
```r
library(rms)

x.1 <- rnorm(20)
x.2 <- rnorm(20)
x.3 <- rnorm(20)
y <- x.1 + x.2 + x.3 + x.1 * x.2 + rnorm(20)

fit <- ols(y ~ x.1 + x.2 + x.3)

## please?
# visreg::visreg(fit)
```

**Comment by pbreheny** [comment]
I don't understand what you're asking for.  The code

```r
visreg::visreg(fit)
```

works just fine for your example above.  Does it not work for you?

**Comment by dylanbeaudette** [comment]
Wow! I was using my own examples to test and something strange must have happened. Sorry about that!

For the record the following works as expected:
```r
library(rms)
library(visreg)

x.1 <- rnorm(20)
x.2 <- rnorm(20)
x.3 <- rnorm(20)
y <- x.1 + x.2 + x.3 + x.1 * x.2 + rnorm(20)

fit1 <- ols(y ~ x.1 + x.2 + x.3)
fit2 <- ols(y ~ rcs(x.1, 3) + x.2 + x.3)

par(mfrow=c(2,3))

# works
visreg(fit1)
visreg(fit2)
```

**Comment by dylanbeaudette** [comment]
I did notice one small issue: the y-axis labels are

**Comment by pbreheny** [comment]
In general, when you pass an option to `visreg()`, that option is passed along to the relevant `predict()` function as well.  Sometimes this results in a plotting option being passed to `predict()`; usually this doesn't cause a problem, but that seems not to be the case with `predict.ols()`.  I suppose I could give some thought as to whether this behavior could be improved, but as visreg is currently designed, you'll have to split up your call to `visreg()` and `plot()`:

```r
v <- visreg(fit, 'x.1')
plot(v, main='main')
```

**Comment by dylanbeaudette** [comment]
Thanks for the suggestions!

I was able to get the desired output using:
```r
p <- visreg( fit, plot=FALSE)
plot(p, main='main', ylab='ylab', ...)
```
