### ISSUE TITLE
strip.names not working correctly with ggplot

### ISSUE THREAD

**Issue by manuSrep** [pbreheny/visreg#85]
I am trying to use the strip.names parameter with a character vector like (strip.names=c("c1:yes", "c2"no) )
It works fine for gg=FALSE but only level values are shown for gg=TRUE as if strip.names=FALSE

visreg version 2.6.1
ggplot2 version 3.3.0

I assume there is a bug, but even if not any help is much appreciated

**Comment by pbreheny** [comment]
Thanks for bringing this to my attention!  This is fixed now on the GitHub version (visreg >= 2.6.1.1).
